[project]
name = "biological-scenarios-generation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "neo4j>=5.28.2",
    "python-libsbml>=5.20.5",
    "typing-extensions>=4.15.0",
]

[dependency-groups]
dev = []
