services:
  mongo:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=openbox
      - MONGO_INITDB_ROOT_PASSWORD=openbox
      - MONGO_INITDB_DATABASE=openbox

  open-box:
    build:
      context: .
      dockerfile: services/open-box.Dockerfile
    depends_on:
      - mongo
    ports:
      - 8000:8000
    expose:
      - "8000"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: orchestrator
      POSTGRES_PASSWORD: orchestrator

volumes:
  pg_migrations:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./
