services:
  mongo:
    image: mongo 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=openbox
      - MONGO_INITDB_ROOT_PASSWORD=openbox
      - MONGO_INITDB_DATABASE=openbox
    networks:
      - virtual_machine

  open-box:
    build:
      context: .
      dockerfile: services/open-box.Dockerfile
    depends_on:
      - mongo
    ports:
      - 8000:8000
    expose:
      - "8000"
    networks:
      - virtual_machine

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: orchestrator
      POSTGRES_PASSWORD: orchestrator
    networks:
      - virtual_machine

  orchestrator:
    build:
      context: .
      dockerfile: services/orchestrator.Dockerfile
    volumes:
      - orchestrator_app:/app
    ports:
      - 8080:8080
    expose:
      - "8080"
    depends_on:
      - postgres
      - open-box
      - slurmctld
    networks:
      - virtual_machine

volumes:
  orchestrator_app:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./ 
  pg_migrations:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./

networks:
  virtual_machine:
    driver: bridge
